yarnPath: .yarn/releases/yarn-4.5.1.cjs
nodeLinker: node-modules

npmScopes:
  "egaranti":
    npmAlwaysAuth: true
    npmAuthToken: "NPM_AUTH_TOKEN"
    npmRegistryServer: "https://npm.pkg.github.com"
