yarnPath: .yarn/releases/yarn-4.6.0.cjs
nodeLinker: node-modules

npmScopes:
  "egaranti":
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_AUTH_TOKEN}
    npmRegistryServer: "https://npm.pkg.github.com"
